SET SCHEMA 'hr';

SELECT *
FROM employees emp JOIN departments dep USING (department_id);

SET SCHEMA 'northwind'

SELECT *
FROM ORDERS JOIN SHIPPERS ON (SHIPP_VIA = SHIPEER_ID);

SELECT *
FROM ORDERS O JOIN SHIPPERS S ON (O.SHIP_VIA = S.SHIPPERS_ID);
WHERE ORDER_DATE::text LIKE '1996-%';

SELECT *
FROM ORDERS O JOIN SHIPPERS S ON (O.SHIP_VIA = S.SHIPPERS_ID);
       JOIN ORDER_DETAILS USING (ORDER_ID);
WHERE ORDER_DATE::text LIKE '1996-%';
